export const accentThemes = {
  lavender: {
    borderClass: "border-[#7F56D9]",
    homeShadowClass: "shadow-[6px_6px_0_#7F56D9]",
    homeHoverShadowClass: "hover:shadow-[9px_9px_0_#7F56D9]",
    projectsShadowClass: "shadow-[8px_8px_0_#7F56D9]",
    projectsHoverShadowClass: "hover:shadow-[11px_11px_0_#7F56D9]",
    dotClass: "bg-[#7F56D9]",
    accentBgClass: "bg-[#7F56D9]",
    accentTextClass: "text-[#7F56D9]",
    onAccentTextClass: "text-white",
    tintBgClass: "bg-[#F3E8FF]",
  },
  tangerine: {
    borderClass: "border-[#F97316]",
    homeShadowClass: "shadow-[6px_6px_0_#F97316]",
    homeHoverShadowClass: "hover:shadow-[9px_9px_0_#F97316]",
    projectsShadowClass: "shadow-[8px_8px_0_#F97316]",
    projectsHoverShadowClass: "hover:shadow-[11px_11px_0_#F97316]",
    dotClass: "bg-[#F97316]",
    accentBgClass: "bg-[#F97316]",
    accentTextClass: "text-[#F97316]",
    onAccentTextClass: "text-white",
    tintBgClass: "bg-[#FFEAD5]",
  },
  emerald: {
    borderClass: "border-[#10B981]",
    homeShadowClass: "shadow-[6px_6px_0_#10B981]",
    homeHoverShadowClass: "hover:shadow-[9px_9px_0_#10B981]",
    projectsShadowClass: "shadow-[8px_8px_0_#10B981]",
    projectsHoverShadowClass: "hover:shadow-[11px_11px_0_#10B981]",
    dotClass: "bg-[#10B981]",
    accentBgClass: "bg-[#10B981]",
    accentTextClass: "text-[#10B981]",
    onAccentTextClass: "text-white",
    tintBgClass: "bg-[#D1FAE5]",
  },
  cobalt: {
    borderClass: "border-[#3B82F6]",
    homeShadowClass: "shadow-[6px_6px_0_#3B82F6]",
    homeHoverShadowClass: "hover:shadow-[9px_9px_0_#3B82F6]",
    projectsShadowClass: "shadow-[8px_8px_0_#3B82F6]",
    projectsHoverShadowClass: "hover:shadow-[11px_11px_0_#3B82F6]",
    dotClass: "bg-[#3B82F6]",
    accentBgClass: "bg-[#3B82F6]",
    accentTextClass: "text-[#3B82F6]",
    onAccentTextClass: "text-white",
    tintBgClass: "bg-[#DBEAFE]",
  },
  fuchsia: {
    borderClass: "border-[#EC4899]",
    homeShadowClass: "shadow-[6px_6px_0_#EC4899]",
    homeHoverShadowClass: "hover:shadow-[9px_9px_0_#EC4899]",
    projectsShadowClass: "shadow-[8px_8px_0_#EC4899]",
    projectsHoverShadowClass: "hover:shadow-[11px_11px_0_#EC4899]",
    dotClass: "bg-[#EC4899]",
    accentBgClass: "bg-[#EC4899]",
    accentTextClass: "text-[#EC4899]",
    onAccentTextClass: "text-white",
    tintBgClass: "bg-[#FCE7F3]",
  },
  sky: {
    borderClass: "border-[#0EA5E9]",
    homeShadowClass: "shadow-[6px_6px_0_#0EA5E9]",
    homeHoverShadowClass: "hover:shadow-[9px_9px_0_#0EA5E9]",
    projectsShadowClass: "shadow-[8px_8px_0_#0EA5E9]",
    projectsHoverShadowClass: "hover:shadow-[11px_11px_0_#0EA5E9]",
    dotClass: "bg-[#0EA5E9]",
    accentBgClass: "bg-[#0EA5E9]",
    accentTextClass: "text-[#0EA5E9]",
    onAccentTextClass: "text-white",
    tintBgClass: "bg-[#E0F2FE]",
  },
  amber: {
    borderClass: "border-[#F59E0B]",
    homeShadowClass: "shadow-[6px_6px_0_#F59E0B]",
    homeHoverShadowClass: "hover:shadow-[9px_9px_0_#F59E0B]",
    projectsShadowClass: "shadow-[8px_8px_0_#F59E0B]",
    projectsHoverShadowClass: "hover:shadow-[11px_11px_0_#F59E0B]",
    dotClass: "bg-[#F59E0B]",
    accentBgClass: "bg-[#F59E0B]",
    accentTextClass: "text-[#F59E0B]",
    onAccentTextClass: "text-[#111111]",
    tintBgClass: "bg-[#FEF3C7]",
  },
  rosewood: {
    borderClass: "border-[#DC2626]",
    homeShadowClass: "shadow-[6px_6px_0_#DC2626]",
    homeHoverShadowClass: "hover:shadow-[9px_9px_0_#DC2626]",
    projectsShadowClass: "shadow-[8px_8px_0_#DC2626]",
    projectsHoverShadowClass: "hover:shadow-[11px_11px_0_#DC2626]",
    dotClass: "bg-[#DC2626]",
    accentBgClass: "bg-[#DC2626]",
    accentTextClass: "text-[#DC2626]",
    onAccentTextClass: "text-white",
    tintBgClass: "bg-[#FEE2E2]",
  },
  mint: {
    borderClass: "border-[#14B8A6]",
    homeShadowClass: "shadow-[6px_6px_0_#14B8A6]",
    homeHoverShadowClass: "hover:shadow-[9px_9px_0_#14B8A6]",
    projectsShadowClass: "shadow-[8px_8px_0_#14B8A6]",
    projectsHoverShadowClass: "hover:shadow-[11px_11px_0_#14B8A6]",
    dotClass: "bg-[#14B8A6]",
    accentBgClass: "bg-[#14B8A6]",
    accentTextClass: "text-[#14B8A6]",
    onAccentTextClass: "text-white",
    tintBgClass: "bg-[#CCFBF1]",
  },
} as const;

export type AccentKey = keyof typeof accentThemes;

export const accentKeys = Object.keys(accentThemes) as AccentKey[];

export const getRandomAccentKey = (): AccentKey =>
  accentKeys[Math.floor(Math.random() * accentKeys.length)];

export const getAccentTheme = (key: AccentKey) => accentThemes[key];
